# https://hub.docker.com/_/debian
FROM debian:bullseye
LABEL org.opencontainers.image.authors="githubfoam"


RUN apt-get update -qy && \ 
    apt-get dist-upgrade -yq && \
    apt-get purge unattended-upgrades && \
    apt-get clean all
    
WORKDIR /tmp